//
// Created by st007 on 19-2-1.
//

#ifndef DESIGNPATTERN_CUNSHARECONCRETEFLYWEIGHT_H
#define DESIGNPATTERN_CUNSHARECONCRETEFLYWEIGHT_H


class CUnshareConcreteFlyweight {

};


#endif //DESIGNPATTERN_CUNSHARECONCRETEFLYWEIGHT_H
